import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f7f7f7',
    paddingHorizontal: 20,
    paddingTop: 30,
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
    paddingHorizontal: 10,
  },
  searchBar: {
    flex: 1,
    height: 40,
    backgroundColor: '#fff',
    borderRadius: 30,
    paddingHorizontal: 20,
    fontSize: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 5,
  },
  searchLoader: {
    marginLeft: 10,
  },
  header: {
    fontSize: 30,
    fontWeight: '600',
    textAlign: 'center',
    marginVertical: 20,
    color: '#333',
    fontFamily: 'Avenir',
  },
  citiesScrollView: {
    paddingBottom: 20,
  },
  cityCard: {
    backgroundColor: '#fff',
    borderRadius: 15,
    marginVertical: 15,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.2,
    shadowRadius: 15,
    elevation: 10,
  },
  cityImage: {
    width: '100%',
    height: 200,
    resizeMode: 'cover',
    borderTopLeftRadius: 15,
    borderTopRightRadius: 15,
  },
  cityInfo: {
    padding: 20,
  },
  cityName: {
    fontSize: 22,
    fontWeight: '600',
    color: '#333',
    marginBottom: 5,
    fontFamily: 'Avenir',
  },
  cityDescription: {
    fontSize: 16,
    color: '#666',
    lineHeight: 22,
    marginBottom: 15,
    fontFamily: 'Avenir',
  },
  exploreButton: {
    backgroundColor: '#00bcd4',
    paddingVertical: 12,
    paddingHorizontal: 25,
    borderRadius: 30,
    alignItems: 'center',
    marginTop: 15,
    shadowColor: '#00bcd4',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.15,
    shadowRadius: 10,
    elevation: 5,
  },
  exploreButtonText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '700',
    fontFamily: 'Avenir',
  },
  searchResultButtonsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 15,
  },
  searchResultButton: {
    backgroundColor: '#007bff',
    paddingVertical: 12,
    paddingHorizontal: 25,
    borderRadius: 30,
    alignItems: 'center',
    flex: 1,
    marginHorizontal: 5,
    shadowColor: '#007bff',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.15,
    shadowRadius: 10,
    elevation: 5,
  },
  searchResultButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
    fontFamily: 'Avenir',
  },

  // New back button style
  backButton: {
    position: 'absolute',
    top: 5,
    left: 6,
    backgroundColor: '#e0e0e0',
    borderRadius: 30,
    padding: 5,
    elevation: 5,
    justifyContent: 'center',
    alignItems: 'center',
  },
});
